- name: add ubuntu to sudoers
  lineinfile: "dest=/etc/sudoers regexp='^ubuntu ALL' line='ubuntu ALL=(ALL) NOPASSWD: ALL'"

- name: install dependencies
  apt: name={{ item }} update_cache=yes
  with_items:
    - python3-dev
    - git
    - curl
    - libpq-dev

- name: copy id_rsa keys
  copy: src={{ item }} dest=/home/ubuntu/.ssh/ mode=0600
  sudo_user: ubuntu
  with_items:
    - id_rsa
    - id_rsa.pub

- name: git checkout
  git: repo=git@github.com:priidukull/twitter-cms.git dest=/home/ubuntu/app accept_hostkey=yes force=yes
  sudo_user: ubuntu
  tags: checkout

- name: install pip3
  shell: curl -L https://raw.github.com/pypa/pip/master/contrib/get-pip.py | sudo python3 creates=/usr/local/bin/pip3
  tags: pip3

- name: set pythonpath
  lineinfile: dest=/home/ubuntu/.bashrc regexp='PYTHONPATH' insertbefore=BOF line='export PYTHONPATH=/home/ubuntu/app:/home/ubuntu/.local/lib/python3.4/site-packages'

- name: set environment
  lineinfile: dest=/home/ubuntu/.bashrc regexp='ENVIRONMENT' insertbefore=BOF line='export ENVIRONMENT={{ env }}'
  sudo_user: ubuntu

- name: set logdir
  lineinfile: dest=/home/ubuntu/.bashrc regexp='LOGDIR' insertbefore=BOF line='export LOGDIR=/home/ubuntu/log'

- name: create log directory
  file: path=/home/ubuntu/log state=directory
  sudo_user: ubuntu

- name: install app requirements
  pip: executable=pip3 requirements=/home/ubuntu/app/requirements.txt extra_args='--user'
  sudo_user: ubuntu
